name: Trigger PF-schema check workflow

on:
  push:
    paths:
      - 'subgraphs/sb1.graphql'

jobs:
  trigger_pf_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      #- name: Install dependencies
        #run: npm ci

      - name: Trigger PF Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: sheikhasim/graphql-demo-PF
          event-type: run_pf_workflow
          client-payload: '{"subgraphPath": "./subgraphs/sb1.graphql"}'
