name: Trigger API endpoint and wait for response on PR

on:
  pull_request_target:
    types:
      opened
    paths:
      - 'subgraphs/sb1.graphql'
  workflow_dispatch:

permissions:
  id-token: write # This is required for AWS OIDC connection
  contents: read # This is required for actions/checkout

jobs:
  trigger_api_and_wait:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Make API request
        id: api-request
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -D - https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev)
          body=$(curl -s https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev)
          echo "::set-output name=response_code::$response"
          echo "::set-output name=response_body::$body"

      # - name: Print API status
      #   run: |
      #     response_code=${{ steps.api-request.outputs.response_code }}
      #     numeric_code=${response_code#* }
      #     if [ "$numeric_code" -eq 200 ]; then
      #       echo "API is a success"
      #     else
      #       echo "API is a failure"
      #     fi


      - name: Dummy Step
        #if: steps.api-request.outputs.response_code == 200
        run: |
          response_code=${{ steps.api-request.outputs.response_code }}
          echo "Response code: $response_code"

