name: Trigger API endpoint and wait for response on PR

on:
  pull_request_target:
    types:
      opened
    paths:
      - 'subgraphs/sb1.graphql'
  workflow_dispatch:

permissions:
  id-token: write # This is required for AWS OIDC connection
  contents: read # This is required for actions/checkout

jobs:
  trigger_api_and_wait:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      #- name: Trigger API endpoint and wait
       # id: api_request
        #run: |
          # Make the API call and store the rsteps.api_request.outputs.workflow_success == "true"esponse
          #API_RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"subgraph": "subgraphs/sb1.graphql"}' https://example.com/api/endpoint)

          # Check the response and determine if it's successful or not
          #if [[ $API_RESPONSE == *"success"* ]]; then
           # echo "::set-output name=api_success::true"
          #else
           # echo "::set-output name=api_success::false"
          #fi
      - name: Make API request
        id: api-request
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://i30fveepxc.execute-api.us-east-1.amazonaws.com/dev)
          echo "::set-output name=response_code::$response"

      - name: Print API status
        run: |
          response_code=${{ steps.api-request.outputs.response_code }}
          if [ "$response_code" -eq 200 ]; then
            echo "API is a success"
          else
            echo "API is a failure"
          fi
